-- Supabase schema for the portfolio contact form.
-- This table is intentionally separate from any product/order tables.
create table if not exists public.portfolio_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 160),
  subject text not null check (char_length(subject) between 1 and 180),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.portfolio_messages enable row level security;

-- No anonymous direct INSERT policy is created.
-- The Vercel API route uses the server-only service-role key.
-- This prevents the service credential from ever reaching the browser.
revoke all on table public.portfolio_messages from anon, authenticated;
grant usage on schema public to anon, authenticated;
